# Site
repository: a-pucci/a-pucci.github.io
favicon: images/favicon.ico

# Personal info
name: Alessandro Pucci
title: Unity3D Developer
email: a_pucci@hotmail.it
phone: "+393476670548"
# website: a-pucci.it
curriculum: a_pucci_cv.pdf

# Social links
twitter_username: a_pucci90
github_username:  a-pucci
gitlab_username: a-pucci
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: a-pucci
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
      Hi, my name is Alessandro Pucci and i am a Unity3D developer.

      I grew up with a SNES controller in my hands playing Donkey Kong and getting fascinated about videogames.

      After some years attending computer science courses at Siena University, i choosed to pursue my passion for games and start searching something that could fit me better.

      One cold day of October 2016 i stumbled in [Event Horizon School](http://eventhorizoncg.com/it/){:target="_blank"}, a game dev school, so i decided to sign up the day next.

      
      In 2019 I completed the studies with a final grade of 30/30.
      Currently I am working as Game Programming assistant professor at [TheSign Comics & Arts Academy](https://thesign.academy/){:target="_blank"}, a partner of Event Horizon School in Florence.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Some of my other interests and hobbies are:

  - Playing guitar

  I've been playing guitar since i was 18 years old.
  Studying this instrument helped me increase my focus, since i had to do repetitive excercises for hours, and playing in a band was usefull in overcoming my shyness.

  - Arduino

  One of my interests is Arduino and automation. My first project was a sort of domotics for my bedroom where i could control all the room lights from an app.

  [Arduino Projects](https://github.com/a-pucci/Arduino_Projects){:target="_blank"}


# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme # (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]

github: [metadata]
